# Generated by Django 3.2.12 on 2022-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poit_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('Accuracy', models.IntegerField()),
                ('Code', models.IntegerField()),
                ('Power', models.IntegerField()),
            ],
        ),
    ]
