# Generated by Django 3.2.12 on 2022-04-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20220324_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField(max_length=6000)),
                ('min', models.IntegerField(max_length=6000)),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
