# Generated by Django 3.2.12 on 2022-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color',
            name='min',
            field=models.IntegerField(),
        ),
    ]
