# Generated by Django 3.2.12 on 2022-04-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20220404_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='color_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(max_length=1000)),
                ('distance', models.IntegerField(max_length=1000)),
                ('distribution', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
