# Generated by Django 3.2.12 on 2022-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_color_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_info',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_info',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='color_info',
            name='distribution',
            field=models.IntegerField(),
        ),
    ]
