# Generated by Django 3.2.12 on 2022-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20220423_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_info',
            name='distribution',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
