# Generated by Django 3.2.12 on 2022-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_color_info_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_info',
            name='distribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
