# Generated by Django 3.2.12 on 2022-04-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20220430_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color_info',
        ),
        migrations.RemoveField(
            model_name='color_param',
            name='color',
        ),
    ]
