# Generated by Django 3.2.12 on 2022-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20220430_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_param',
            name='paraeter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
