# Generated by Django 3.2.12 on 2022-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_color_param_paraeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='tech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
