# Generated by Django 3.2.12 on 2022-06-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('map', '0017_color_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField()),
                ('mean', models.IntegerField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('median', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('std', models.IntegerField()),
                ('variance', models.IntegerField()),
                ('ci', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Color_param',
            new_name='Color_Info',
        ),
        migrations.RenameModel(
            old_name='Poit_Info',
            new_name='Point_Info',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Ranges',
        ),
        migrations.RenameField(
            model_name='color_info',
            old_name='paraeter',
            new_name='parameter',
        ),
    ]
