# Generated by Django 3.2.12 on 2022-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20220627_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static_info',
            name='ci',
        ),
        migrations.AddField(
            model_name='static_info',
            name='ci_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='static_info',
            name='ci_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='mean',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='median',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='mode',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='std',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='static_info',
            name='variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
