# Generated by Django 3.2.12 on 2022-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20220627_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_info',
            name='ARFCN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='CellID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='Color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='LAC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='Node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='PLMNID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='Quality',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='Scan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='point_info',
            name='technology',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='point_info',
            name='Power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='point_info',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='point_info',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
