# Generated by Django 3.2.12 on 2022-06-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_auto_20220627_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_info',
            old_name='ARFCN',
            new_name='aRFCN',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Accuracy',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='CellID',
            new_name='cellId',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Time',
            new_name='ime',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='LAC',
            new_name='lac',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Node',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='PLMNID',
            new_name='plmnId',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Power',
            new_name='power',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Quality',
            new_name='quality',
        ),
        migrations.RenameField(
            model_name='point_info',
            old_name='Scan',
            new_name='scan',
        ),
    ]
