# Generated by Django 3.2.12 on 2022-06-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_auto_20220627_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_info',
            old_name='aRFCN',
            new_name='arfcn',
        ),
    ]
