# Generated by Django 3.2.12 on 2022-06-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_rename_arfcn_point_info_arfcn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_info',
            old_name='ime',
            new_name='time',
        ),
    ]
