# Generated by Django 3.2.12 on 2022-06-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_rename_ime_point_info_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point_info',
            old_name='Color',
            new_name='color',
        ),
    ]
