# Generated by Django 3.2.12 on 2022-06-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_rename_color_point_info_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_info',
            name='accuracy',
        ),
    ]
