# Generated by Django 3.2.12 on 2022-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_remove_point_info_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranges',
            name='parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
