# Generated by Django 3.2.12 on 2022-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_point_info_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_info',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
