# Generated by Django 3.2.12 on 2022-07-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='regin_name',
            new_name='region_name',
        ),
    ]
