# Generated by Django 3.2.12 on 2022-07-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_rename_regin_name_region_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_info',
            name='region',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.region'),
        ),
    ]
