# Generated by Django 3.2.12 on 2022-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0036_alter_color_info_color_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_info',
            name='color_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
