# Generated by Django 3.2.12 on 2022-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_alter_color_info_color_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('distribution', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tech', models.CharField(max_length=2)),
                ('band', models.CharField(blank=True, max_length=100, null=True)),
                ('freq', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
