# Generated by Django 3.2.12 on 2022-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
