# Generated by Django 3.2.12 on 2022-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_table_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
