# Generated by Django 3.2.12 on 2022-07-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_auto_20220722_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tech',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
