# Generated by Django 3.2.12 on 2022-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_alter_table_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranges',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
