# Generated by Django 3.2.12 on 2022-08-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_ranges_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point_Info',
        ),
    ]
