# Generated by Django 3.2.12 on 2022-08-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_point_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point_Info',
        ),
    ]
