# Generated by Django 3.2.12 on 2022-08-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_delete_point_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('code', models.IntegerField()),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('node', models.IntegerField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=50, null=True)),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('plmnId', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('cellId', models.BigIntegerField(blank=True, null=True)),
                ('scan', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('region', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.region')),
            ],
        ),
    ]
