# Generated by Django 3.2.12 on 2022-09-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0050_result_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_info',
            name='tech',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
