# Generated by Django 3.2.12 on 2022-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0052_result_table_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static_info',
            name='ci_max',
        ),
        migrations.RemoveField(
            model_name='static_info',
            name='ci_min',
        ),
        migrations.AddField(
            model_name='static_info',
            name='ci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
