# Generated by Django 3.2.12 on 2022-09-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0053_auto_20220915_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static_info',
            name='variance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True),
        ),
    ]
