# Generated by Django 3.2.12 on 2022-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0054_alter_static_info_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static_info',
            name='variance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
