# Generated by Django 3.2.12 on 2022-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0055_alter_static_info_variance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranges',
            name='max',
        ),
        migrations.RemoveField(
            model_name='ranges',
            name='min',
        ),
        migrations.AddField(
            model_name='ranges',
            name='rang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
